source "https://rubygems.org"

ruby "2.7.3"

gem "roda", ">= 3.43"
gem "tilt", ">= 2.0"

# web server
gem "puma"

# websocket gem
gem "litecable"
gem "websocket"

# database stuff
gem "sequel"
gem "sqlite3"
