source "https://rubygems.org"

ruby "2.5.8"

gem "sinatra", require: "sinatra/base"
gem "sinatra-contrib", require: false

# web server
gem "puma"

# websocket gem
gem "litecable"
gem "websocket"

# database stuff
gem "sequel"
gem "sqlite3"
